"""
Query API for the RAG Agent Service.

This module exposes the `/api/query` endpoint, which:
- Accepts a natural-language query
- Retrieves similar chunks from the vector store
- Delegates answer construction to the RAG pipeline
"""

from fastapi import APIRouter, Depends
from qdrant_client import QdrantClient
from sentence_transformers import SentenceTransformer

from app.deps import get_qdrant_client, get_embedding_model
from app.rag.models import QueryRequest, QueryResponse
from app.rag.pipeline import run_rag_pipeline
from app.rag.vectorstore import VectorStore

# Router is mounted under /api in app.main
router = APIRouter(tags=["query"])


def get_vector_store(client: QdrantClient = Depends(get_qdrant_client)) -> VectorStore:
    """
    Dependency that provides a VectorStore instance backed by Qdrant.

    Args:
        client: QdrantClient created via `get_qdrant_client`.

    Returns:
        VectorStore: Thin wrapper around Qdrant collections.
    """
    return VectorStore(client)


@router.post(
    "/query",
    summary="Run a RAG query",
    response_model=QueryResponse,
)
async def query_rag(
    request: QueryRequest,
    vector_store: VectorStore = Depends(get_vector_store),
    embedder: SentenceTransformer = Depends(get_embedding_model),
) -> QueryResponse:
    """
    Execute a retrieval-augmented generation (RAG) query.

    This endpoint:
    - Encodes the query with the shared embedding model
    - Performs a vector search in Qdrant using `VectorStore`
    - Returns retrieved documents plus an answer generated by the pipeline

    Args:
        request: Query text and `top_k` setting.
        vector_store: VectorStore used for similarity search.
        embedder: Shared sentence-transformers model for query embeddings.

    Returns:
        QueryResponse: Answer text plus the list of retrieved documents.
    """
    return run_rag_pipeline(request, vector_store, embedder)
